[package]
name = "protos-common"
version = "0.1.0"
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
prost = { workspace = true }
serde = { workspace = true }
tonic = { workspace = true }
tonic-prost = { workspace = true }
uuid = { workspace = true }

[build-dependencies]
tonic-prost-build = { version = "0.14.3" }
build-deps = { workspace = true }

[lints]
workspace = true

[lib]
test = false
doctest = false
