[package]
name = "pc-observatory-models"
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true

[lib]
path = "src/lib.rs"
test = true
doctest = false

[dependencies]
chrono = { workspace = true }
pc-observatory-types = { workspace = true }
polars-descriptions = { workspace = true, optional = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
uuid = { workspace = true }

[features]
server = ["dep:schemars", "pc-observatory-types/server"]
convert = ["dep:polars-descriptions"]

[lints]
workspace = true
